# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x0qXBHG27V9kZWdlhvXUS30fupGwa7Z-
"""



"""Assignment 1"""



# Calculate the length of the transition curve

# Input values from the user
V = float(input("Enter the value of design speed: "))
R = float(input("Enter the value of radius of curvature: "))
N = float(input("Enter the value of slope (in decimal form, e.g., 0.02 for 2%): "))
W = float(input("Enter the value of width of road including extra widening: "))
emax = float(input("Enter the value for plain terrain: "))

# Calculate super elevation (ecal)
ecal = (V * V) / (225 * R)
print("The value of super elevation:", ecal)

# Check if ecal is less than emax
if ecal < emax:
    Ls = (emax * N * W) / 2
    print("Length of transition curve:", Ls)
else:
    print("No transition curve needed.")

