# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x0qXBHG27V9kZWdlhvXUS30fupGwa7Z-
"""



"""Assignment 6"""

# Calculating the stress by Boussineq's Theory
Q= int(input("Enter the value of given load :"))
z= int(input("Enter the distance of vertical stress :"))
r= int(input("Enter the distance ofhorizntal stress:"))
stress = ((3*Q*(1/(1+(r/z)**2)) **2.5))/(2%3.14*(z**2))
print("The value of stress is", stress)