# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x0qXBHG27V9kZWdlhvXUS30fupGwa7Z-
"""



"""Assignment 9"""

#To find BOD at 7th day 25C
# To find Decay Coefficient at 25C
K1 = float(input("Decay Coefficient at reference temperature (K1):"))
T1 = float(input("Temperature of 3rd day BOD (T1):"))
T2 = float(input("Temperature of 7th day BOD (T2):"))

K2 = K1 * (1.047 ** (T1 - T2))
print("The value of K2 is:", K2)

# To find Ultimate BOD
e = 2.718
print("The value of e is:", e)

B1 = float(input("BOD at 3rd day 20°C (B1):"))
t = float(input("Time in days for finding B1:"))
E = 1 - e ** (-0.23 * t)
print("The value of E is:", E)

B10 = B1 / E
print("The value of B10 is:", B10)

# To find BOD at 7th day 25°C
B2 = float(input("BOD at 7th day 25°C (B2):"))
t1 = float(input("Time in days for finding B2:"))
E1 = 1 - e ** (-0.289 * t1)
print("The value of E1 is:", E1)

B7 = B10 * E1
print("The value of B7 is:", B7)

M = float(input("Enter the value of initial mass: "))
S = float(input("Enter the value of solid containing sludge in percentage: "))
Gs = float(input("Enter the value of Specific gravity of sludge solid: "))
RhoW = float(input("Enter the value of density of water: "))

Ws = (S / M) * 100
m = M - Ws
print("The value of mass of water:", m)
print("The value of Solid Content in sludge:", Ws)

Vw = m / RhoW
print("The Value of Volume of water:", Vw)

RhoS = Gs * RhoW
print("The value of Density of solid content in sludge:", RhoS)

Vs = (Ws / (Gs * RhoS))
print("The value of volume of solid content in sludge:", Vs)

Vt = Vw + Vs
print("The value of total volume of solid content in sludge:", Vt)

RhoSL = M / Vt
print("The value of Density of sludge removed from aeration:", RhoSL)

9