# -*- coding: utf-8 -*-
"""CPCE Assignments 1 to 10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZjKfni8V7Epe77IGGQ8u1DxNwppM_8nw

Assignment 1
"""

# To find the downstream depth of open channel # Given Data
Q= float(input("Enter the value of Discharge:"))
T= int(input("Enter the value of top width:"))
g= float(input("Enter the value of acceleration due to Gravity:"))
y1= float(input("Enter the value of upstream depth:"))
Z= float(input("Enter the Value of hump:")) #Dicharge per meter width
q=Q/T
print("The value of discharge per meter width is:", q) #Area Calculation
A1= T*y1
print("The value of upstream area is:", A1) # Calculation of Froude Number
Fr1 = ((Q*Q*T)/(g*A1* A1 *A1))**0.5
print("The value of Froude number is:", Fr1)
if Fr1>1:
  print("The flow is Super Critical Flow")
else:
  print("The flow is Sub Critical Flow")
  #Upstream Energy
E1=(y1+(Q*Q)/(2 *g*A1 *A1))
print("The value of Energy at initial Section is:", E1) #Downstream Energy
E2=E1-Z
print("The value of downstream Energy E2 is:", E2) #Critical Depth
yc=(q*q/g)**0.3333
print("The Value of critical depth is:", yc)
Ec=1.5*yc
print("The value of critical Energy is:", Ec)
if Ec>E2:
  print("Chocking Conditlon")
else:
  print ("SAFE")
#Calculation of Zmax
Zmax=E1-Ec
print("The value of maxinmum hump is:", Zmax)

# To find the downstream depth of open channel # Given Data
Q= float(input("Enter the value of Discharge:"))
T= int(input("Enter the value of top width:"))
g= float(input("Enter the value of acceleration due to Gravity:"))
y1= float(input("Enter the value of upstream depth:"))
Z= float(input("Enter the Value of hump:")) #Dicharge per meter width
q=Q/T
print("The value of discharge per meter width is:", q) #Area Calculation
A1= T*y1
print("The value of upstream area is:", A1) # Calculation of Froude Number
Fr1 = ((Q*Q*T)/(g*A1* A1 *A1))**0.5
print("The value of Froude number is:", Fr1)
if Fr1>1:
  print("The flow is Super Critical Flow")
else:
  print("The flow is Sub Critical Flow") #Upstream Energy
E1=(y1+(Q*Q)/(2 *g*A1 *A1))
print("The value of Energy at initial Section is:", E1) #Downstream Energy
E2=E1-Z
print("The value of downstream Energy E2 is:", E2) #Critical Depth
yc=(q*q/g)**0.3333
print("The Value of critical depth is:", yc)
Ec=1.5*yc
print("The value of critical Energy is:", Ec)
if Ec>E2:
  print("Chocking Conditlon")
else:
  print ("SAFE")
#Calculation of Zmax Zmax=E1-Ec
print("The value of maxinmum hump is:", Zmax)

#To find the downstream depth of open channel #Given Data
Q= int(input("Enter the value of Discharge:"))
B1 = float(input("Enter the value of width at upstream: "))
B2 = float(input("Enter the value of width at downstream: "))
g= float(input("Enter the value of acceleration due to Gravity:"))
yl= int(input("enter the value of upstream depth:"))
#Dicharge per meter width
q1=Q/B1
q2=Q/B2
print("The value of discharge per meter width is: ", q1)
print("The value of discharge per meter width is:", q2)
#Area Calculation
A1=B1*y1
print("The value of upstream area is:", A1) #Calculation of Froude Number
Fr1=((Q*Q*B1)/(g*A1*A1*A1)) **0.5
print("The value of Froude number is:", Fr1)
if Fr1>1:
  print("The flow is Super Critical Flow")
else:
  print("The flow is Sub Critical Flow") #Upstream Energy
E1=y1+((Q*Q)/(2*g*A1*A1))
print("The value of Energy at initial Section is:",E1) #B2min: Any dition
B2min = (27*Q*Q/(8*g*E1*E1*E1))**0.5
print("The value of minimum width to be kept to avoid Chocking is:", B2min)
if B2min > B2:
  print("Chocking Condition")
else:
  print("SAFE") #Critical Depth
yc=((Q*Q)/(B2*B2*g))**0.3333
print ("The Value of critical depth is: ", yc)
Ec=1.5*yc
print("The value of critical Energy is", Ec)

"""ASIGNMENT NO 2 APPLICATION OF PYTHON IN FIELD OF HYDROLOG

Q-1
"""

# Calculation of total Infiltration by Horton's Equation
fo = int(input("Enter the value of initial Infiltration Rate:"))
fc= float (input("Enter the value of Final infiltration Rate:"))
t= int(input("Enter the value of Time:"))
kh= float(input("Enter the value of Decay Coefficient:")) # The total Infiltration is given by:
Fp= fc*t+(fo-fc)/kh
print ("The value of Total Infiltration is:", Fp)

"""Q-2"""

#Calculation of Mean precipitation by theissen's polygon Method #The value of precipitation at Each station is
p1=int(input("Enter the value of rainfall at Station 1:"))
p2= int(input("Enter the value of rainfall at Station 2:"))
p3 =int(input("Enter the value of rainfall at Station 3:"))
p4 =int(input("Enter the value of rainfall at Station 4:"))
p5 =int(input("Enter the value of rainfall at Station 5:"))
#Area for each station
A1= int(input("Enter the value of Catchment Area for raingauge station 1:"))
A2= int(input("Enter the value of Catchment Area for raingauge station 2:"))
A3 =int(input("Enter the value of Catchment Area for raingauge station 3:"))
A4=int(input("Enter the value of Catchment Area for raingauge station 4:"))
A5= int(input("Enter the value of Catchment Area for raingauge station 5:"))
#The total catchment area is
A=A1+A2+A3+A4+A5
print("The value of Total Catchment area is:", A) #Runoff Volume
V=(p1*A1+p2*A2+p3*A3+p4*A4+p5*A5)*2500
print("The runoff volume from the given catchment is:", V) # Mean Precipitation
p=(p1*A1+p2*A2+p3*A3+p4*A4+p5*A5)/A
print ("The value of Mean Precipitalon is:", p)

"""Q-3"""

#Calculation of Mean precipitation by Isohytel Method #The value of precipitation at Each station i
p1= int(input("Enter the value of rainfall at Station 1:"))
p2= int(input("Enter the value of rainfall at Station 2:"))
p3= int(input("Enter the value of rainfall at Station 3:"))
p4= int(input("Enter the value of rainfall at Station 4:"))
p5= int(input("Enter the value of rainfall at Station 5:"))
p6= int(input("Enter the value of rainfall at Station 6:"))
p7= int(input("Enter the value of rainfall at Station 7:"))
p8= int(input("Enter the value of rainfall at Station 8:"))
# Area for each station
A1= int(input("Enter the value of Catchment Area for raingage station 1:"))
A2= int(input("Enter the value of Catchment Area for raingauge station 2:"))
A3= int(input("Enter the value of Catchment Area for raingauge station 3:"))
A4= int(input("Enter the value of Catchnent Area for reingauge station 4:"))
A5= int(input(" Enter the value of Catchment Ares for raingauge station 5:"))
A6= int(input("Enter the value of Catchment Area for raingeuge station 6:"))
A7= int (input("Enter the value of Catchment Area for reingauge station 7:"))
# The total catchment area is
A=A1+A2+A3+A4+A5+A6+A7
print("The value of Total Catchment ar ea is :", A) #Mean Precipitation
p=((p1+p2)*A1/2+(p2+p3)*A2/2+(p3+p4)*A3/2+(p4+p5)*A4/2+(p5+p6)*A5/2+(p6+p7)*A6/2+(p7+p8)*A7/2)/A
print("the value of Mean Precipitalon is:", p)

"""ASSIGNMENT NO 3 -APPLICATION OF PYTHON IN TRANPORTATION ENGINEERING

Q-1
"""

#To Calculate the length of transition curve
V= int(input("Enter the value of design speed:"))
R= int(input("Enter the value of Radius of curvature:"))
N= int(input("Enter the value of slope:"))
W= float(input("Enter the value of width of road including extra widening:"))
emax= float(input("enter the value for plain terain:"))
ecal=(V*V/(225*R))
print("The value of Super elevation:",ecal)
if ecal<emax:
  print(ecal)
else:
  print(emax)
Ls=(emax*N*W/2)
print("The length of transition curve:", Ls)

"""Q-2"""

R = int(input("Constant R:"))
C = int(input("Constant C:"))
import numpy as geek
A = int(input("Total Data Values for EWL Constant:"))
B = int(input("Total Data Values for AADT: "))
EWL_Constant =[]
AADT =[]
for i in range(1,A+1):
  print("Enter EWL Constant:")
  A = float(input())
  EWL_Constant.append(A)
for j in range(1,B+1):
  print("Enter AADT:")
  B = float(input())
  AADT. append (B)
product=geek.dot(EWL_Constant,AADT)
print("Dot Product:\n", product)
Total_EWL = product
print("Total EWL:", Total_EWL)
print("EWL after 60 years:",Total_EWL*1.6)
TI = 1.35*(((1.6*Total_EWL)+((product)/2))**0.11)
print("Traffic Index : ", TI)
Thickness = 0.166*TI*(99-R)/(C**0.2)
print ("Pavement Thickness: ", Thickness, "cm")

"""Q-3"""

P =float (input(" Load in kg: "))
p =float (input(" Tyre pressure kg/cm^2: "))
M = int (input("Total Number of layers in a given Pavement : "))
pi = 3.14159
CBR = []
for i in range (1, M+1):
  print("California Bearing Ratio of Material in %")
CBR_value = float(input())
CBR.append(CBR_value)
T = ((1.75*P)/(CBR_value)-(P/(p*pi)))**0.5
print("Thickness Above this layer: ", T, "cm")
print("Given that bitumen layer of 4 cm")

"""ASSIGNMENT NO 4 - APPLICATION OF PYTHON IN FIELD OF CONCRETE TECHNOLOGY

Q-1
"""

fck = float(input(" Enter the value of characteristic compressive strength:"))
# Experimental Determinations
Gca = float(input ("Enter the value of specific gravity of CA:"))
Gfa = float(input("Enter the value of specific gravity of FA:"))
Gc = float(input("Enter the value of specific gravity of Cement:"))
Water_Density = float(input("Enter the value of Water Density:"))
AGG_Size = float(input("Enter the nominal Size of Aggregate:"))
Nature_of_AGG = input("Nature of Aggregates:")
Slump = float(input("Enter the value of workability of concrete:"))
Admixture = input("Type of Admixture:")
Exposure_Condition = input("Exposure Condition:")
Concreting = input("Type of Concreting:")
Zone = int(input("Zone:"))
# Target Mean Strength
sigma = {10:3.5,15:3.5,20: 4,25:4,30: 5,35: 5,40: 5,45: 5,50: 5,55: 5}
ft=fck+sigma[fck]*1.65
print("Target Mean Strength:",ft,"MPa")
# Maximum free Water Cement Ratio
# Reference IS 456: 2000 Table 5
if(Concreting == "Plain"):
  WC_ratio = {"Mild" : 0.6,"Moderate" :0.6,"Severe" :0.5,"Very Severe" :0.45, "Extreme":0.4}
else:
  WC_ratio ={"Mild": 0.55,"Moderate":0.5,"Severe" :0.45,"Very Severe" :0.45, "Extreme":0.4}
print("W/C Ratio:",WC_ratio[Exposure_Condition] )
WC_ratio = WC_ratio[Exposure_Condition]
# Minimum Cement Content
if(Concreting == "plain"):
  Min_Cement_Content = {"Mild":220,"Moderate": 240,"Severe": 250,
"Very Severe": 260,"Extreme": 280}
else:
  Min_Cement_Content = {"Mild":300,"Moderate": 300,"Severe": 320,
"Very Severe": 340,"Extreme": 360}
print("Minmum Cement Content:", Min_Cement_Content[Exposure_Condition],"kg/m^3") # Water Content
Water_Content={10:208,20:186,40:165}
Water_Content = Water_Content[AGG_Size]
if (Slump == 75):
  Water_Content = Water_Content + Water_Content*0.03
elif (Slump == 100):
  Water_Content = Water_Content + Water_Content*0.06
elif (Slump == 125):
  Water_Content = Water_Content + Water_Content*0.09
elif (Slump == 150):
  Water_Content = Water_Content + Water_Content*0.12
elif (Slump == 175):
  Water_Content = Water_Content + Water_Content*0.15
elif (Slump == 200):
  Water_Content = Water_Content + Water_Content*0.18
if (Nature_of_AGG == "Sub-Angular"):
  Water_Content = Water_Content - 10
elif (Nature_of_AGG == "Gravel"):
  Water_Content = Water_Content - 20
elif (Nature_of_AGG == "Round"):
  Water_Content = Water_Content - 25
if (Admixture == "Plastisizer"):
  Water_Content = Water_Content-(0.1*Water_Content)
elif (Admixture=="Super-plastisizer"):
  Water_Content = Water_Content-(0.2*Water_Content)
print("Water Content:", Water_Content, "kg/m^3") # Cement Content
Cement_Content = Water_Content/WC_ratio
print("CementContent:", Cement_Content, "kg/m^3")
print("As Per IS 456:2000, Maximum allowed Cement Content is 450 kg/m^3")

if (Cement_Content< 450):
  Cement_Content = Cement_Content
else:
  Cement_Content = 450

if Cement_Content< 450:
  print("Safe")


# Volume Calculations
Vol_Cement = Cement_Content/(Gc*Water_Density)
print("Volume of Cemnet:",Vol_Cement,"m^3")
Vol_Water = Water_Content/Water_Density
print("Volume of Water:",Vol_Water,"m^3")
Vol_AGG= 1-Vol_Water-Vol_Cement
print("Volume of Course Aggregates and Fine Aggregates: ",Vol_AGG, "m^3")
Zone_ID ={}
Zone_ID[1]= {10:0.44, 20:0.60, 40:0.69}
Zone_ID[2]={10:0.46, 20:0.62, 40:0.71}
Zone_ID[3]={10:0.48, 20:0.64, 40:0.73}
Zone_ID[4]={10:0.5, 20:0.66, 40:0.75}
Fraction = Zone_ID[Zone] [AGG_Size]
if (WC_ratio==0.5) :
  Fraction=Fraction
elif (WC_ratio==0.45):
 Fraction=Fraction+(0.01*Fraction)
elif (WC_ratio==0.4):
  Fraction=Fraction+(0.02 * Fraction)
elif (WC_ratio==0.55):
  Fraction=Fraction-(0.01*Fraction)
elif (WC_ratio==0.60):
  Fraction=Fraction-(0.02*Fraction)

print("Course Aggregate fraction:", Fraction)
Vol_CA = Vol_AGG*Fraction
print ("Volume of Course Aggregate:", Vol_CA,"m^3")

Vol_FA = Vol_AGG-Vol_CA
print ("Volume of Fine Aggregate: ", Vol_FA,"m^3")

Mass_CA= Vol_CA*Gca* Water_Density
print ("Mass of Course Aggregates: ", Mass_CA, "Kg/m^3")

Mass_FA = Vol_FA*Gfa*Water_Density
print ("Mass of Fine Aggregates:", Mass_FA, "kg/m^3")

# Ratios
print("Weight Batching")
print(Cement_Content/Cement_Content,":", Mass_FA/Cement_Content,":", Mass_CA/Cement_Content,":",Water_Content/Cement_Content)
print("Volume Batching:")
print(Vol_Cement/Vol_Cement,":",Vol_FA/Vol_Cement,":",Vol_CA/Vol_Cement,":",Vol_Water/Vol_Cement)

"""ASSIGNMENT NO 5 - APPLICATION OF PYTHON IN THE FIELD OF REINFIRCED CEMENT CONCRETE

Q-1
"""

#To find the ultimate moment carring capacity of singly r/f beam
fck = float(input("Enter the value of charateristics compressive strength:"))
fy = float(input("Enter the grade of steel:"))
Es = float(input("Enter the value of Modulus of Elasticity of steel:"))
b = float(input("Enter the value of Width:"))
d = float(input("Enter the value of effective depth:"))
d1 = float(input("Enter the value of bar diameter (d1):"))
d2 = float(input("Enter the value of bar diameter (d2):"))
n=int(input("Enter the number of bars"))
Ast1=(n*0.7854*d1*d1)
Ast2=(n*0.7854*d2*d2)
print("The value of area of steel (Ast1):", Ast1)
print("The vaiue of area of steel (Ast2):", Ast2)
#Total area of steel
Ast=Ast1+Ast2
print("The value of area of steel (Ast):", Ast)
#Neutral Axis Factor
ku = 0.0035/(0.0055+(fy/(1.15*Es)))
print("The value of Neutral axis factor (ku):", ku)
#Momenent of Resistance factor
Ru=0.36*fck*ku*(1-(0.42*ku))
print("The value of Moment of Resistance factor (Ru):", Ru)
#Maximum Neutral Axis:
xumax = ku*d
print("The value of maximum neutral axis (xumax):", xumax)
xu = (0.87*fy*Ast)/(0.36*fck*b)
print ("The value of Actual Neutral Axis (xu):", xu)
if xumax>xu:
  print("UNDER REINFORCED")
else:
  print("OVER REINFORCED")
#By Comparing
X = float(input("Enter the value of Neutral Axis:"))
#Moment of Resistance
Mu=0.36*fck*xu*b*(d-(0.42*xu))*10*-6
print("The value of Moment of Resistance is:", Mu)

#Design of Slab #Given Data
#Effective span is already given in question
span= float(input("Enter the value of effective span in meters:"))
b= float(input("Enter the value of width of slab in mm:"))
bs= float(input("Entert the value of Support Width in meters:"))
fck = float(input(" Enter the value of Characteristics Compressive Strength:"))
fy = float(input("Enter the value of grade of steel:"))
Es = float(input("Enter the value of Modulus of Elasticity is:"))
LL = float(input("Enter the value of Live Load:"))
FF = float(input("Enter the value of Floor Finish:"))
Density = float(input("Enter the value of Density of RCC:"))
# Design Constants
# Neutral Axis Factor
ku=0.0035/((0.0055)+(fy/(1.15*Es)))
print("The value of Neutral Axis Factor (ku) is:", ku)
# Moment of Resistan ce Facor
Ru= 0.36*fck*ku*(1-(0.42*ku))
print("The value of Moment Resisteance factor (Ru) is:", Ru)
#Assurming pt 0.5 from fig.4 from IS 456:2007 page no.38
fs=float(input("Ent er the value of Steel Stress of Service:"))
#From Graph find out the Modification Factor
MF=float(input("Enter the value of Modification Factor:"))
#From Clause 23.2.1 Select span/d Ratio
S=float(input("Enter the value of span/d ratio:"))
#Correction Factors
k1=float(input("Enter the value of Correction factor if sapn> 10m (k1):"))
k2= float(input(" Enter the value of Tension r/f correction factor (k2):"))
k3= float(input ("enter the value of Compression r/f correction factor (k3):"))
k4= float (input(" Enter the value of correction factor in case of flanged section (k4):")) # Effective depth
d1=(span*1000)/(S*MF*k1*k2*k3*k4)
print("The value of effective depth as per deflection criteria is:", d1)
# Define Effective depth and overall depth Assuming value of cover
d = float(input("Enter the value of Effective depth in mm (d):"))
D= float(input("Enter the value of Overall depth in mm (D):"))
# Load Calculations
# Self Weight of slab
DL=D*Density/1000
print("The Dead load is:", DL)
# Total Load is
Factor=float(input("Enter the value of partial Safety Factor is: "))
TL=DL+LL+FF
print("The value of total load is:", TL)
Wu=Factor*TL
print("Wu=", Wu)
# Bendingf Moment Calculations (Mu)
Mu= Wu*span*span/8
print("The Value of Bending Moment (Mu) is:", Mu)
# Check for effective depth
d2=(Mu*1000000/(Ru*b))**0.5
print("The value of Effective depth as per Mornent criteria:", d2)
if d2>d:
  print ("Revise the Depth:")
else:
  print ("'SAFE")
d = float(input("Enter the value of Effective depth in mm (d):"))
print("Minimum Steel Calculations")
Astmin = 0.12*b*D/100
print("The value of Minimum steel is:", Astmin)
print("Main Steel calculations'")
Ast=((0.5*fck*b*d)/(fy))*(1-((1-((4.6*Mu*1000000)/(fck*b*d*d)))**0.5))
print("Ast:", Ast)
print("Check for Ast")
if Ast<Astmin:
  print("Take Ast=Astmin")
else:
  print("Ast>Astmin, Hence SAFE")
dia1 = float(input("Enter the value of bar diameter for main steel:"))
dia2 = float(input(" Enter the value of bar diameter for Distribution steel:"))
#Area of bar
ao1 = 0.7854*dia1*dia1
print("The Value of Area of main steel bar (ao1):", ao1)
ao2= 0.7854* dia2*dia2
print("The Value of Area of main steel bar (ao2):", ao2)
# Sapcing Calculations
Spacing1 = ao1*b/Ast
print("The sapcing for main steel bars is;", Spacing1)
Spacing2=ao2*b/Astmin
print("The sapcing for distribution steel bars is;", Spacing2)
print("Check 1 for main steel")
if Spacing1>300:
  print("UNSAFE")
else:
  print("SAFE")
print("'Check 2 for main steel")
if Spacing1 > 3*d:
  print("UNSAFE")
else:
  print("SAFE")
print("Check 1 fon Distribution steel")
if Spacing1>300:
  print("UNSAFE")
else:
  print("SAFE")
print("Check 2 for Distribution steel")
if Spacing1>5*d:
  print("UNSAFE")
else:
  print("SAFE")
print("Approximated values of Sapcing:")
S1= float(input("Enter the value of spacing of main bars:"))
S2=float(input("Enter the value of spacing of distribution bars:"))
Astprovided=ao1*b/S1
print("The provided steel area for main bars at section in mm^2 is:", Astprovided)
Astprodist=ao2*b/S2
print("The provided steel area for distribution bars at section in mm^2 is: ", Astprodist)
# Check for Shear
Vu=(Wu*span/2)-(Wu*((bs/2)-(d/1000)))
print("The value of SF at a Section is:", Vu)
Stress=(Vu*1000)/(b*d)
print("The vaiue of shear stress is:", Stress)
# From table 20 IS 456:2007 page 73
Stressmax = float(input("Enter the value of maximum Shear stress:"))
if Stress>Stressmax:
  print("Crushing will happen")
else:
  print("SAFE")
pt=(100*Ast)/(b*d)*120
print("Enter the value of percentage steel is:", pt)
#From table 19 IS 456:2007 page 73
SS=float(input("Enter the value of Shear Stress is:"))
k=float(input("Enter the value of depth factor:"))
Shear=k*SS
print("The value of shear at section is, Shear")
if Stress>Shear:
  print("Shear Reinforcement Required")
else:
  print("Shear Reinforcement not Required, SAFE")
  # Check for Deflection
ActDEF=span*1000/d
print("The value od span/d is:", ActDEF) # Actual Deflection
MaxDEF=S*MF*k1*k2*k3*k4
print("The permissible deflection is:", MaxDEF)
if MaxDEF>S/d:
  print("SAFE")
else:
  print("UNSAFE")
# Check for Anchorage Length
M1=0.87*fy*Ast*(d*(fy*Ast)/(fck*b))
print("The value of Moment (M1)'", M1)
lo = 8*dia1
La = 1.3*(M1/Vu)+10
print ("The value of Anchorage length is:", La)
# Development Length
bonds = float(input("Enter the value of Bond Stress:"))
Ld = 0.87*fy*dia1/4*bonds*1.6
print("The value of Development length is:", Ld)
if La>Ld:
  print("'SAFE")
else:
  print("increase anchorage")

"""ASSIGNMENT NO 6 APPLICATYION OF PYTHON IN THE FIELD OF SOIL MECHANICS

Q-1
"""

# Stress When depth is constant
Q = float(input("Enter the value of Load in kN:"))
N= int(input("Number of data values of radial distance:"))
pi = 3.14159265359
Z = float(input("Depth:"))
r = []
for i in range (1, N+1):
  print("Enter radial distance in m".format (i))
  Value_r = float(input())
  r.append(Value_r)
  Stress =((3*Q)/(2*pi*Z*Z))*(((1/(1+((Value_r/Z)**2))))**2.5)
  print("Stress:",Stress,"kN/m^2")

"""Q-2"""

# Stress when Radius is Constant
Q = float(input("Enter the value of Load in kN:"))
M= int(input ("Number of data values of depth:"))
pi = 3.14159265359
r = float(input("Radial Distance:"))
Z = []
for j in range (1, M+1):
  print ("Enter depth in z".format (i))
  Value_Z = float(input())
  Z.append(Value_Z)
  Stress = ((3*Q)/(2*pi*Value_Z* Value_Z))*(((1/(1+((r/Value_Z)**2)))))**2.5
  print("Stress:", Stress,"kN/m^2")

"""Q-3"""

# Calculating the stress by Boussineq's Theory
Q= int(input("Enter the value of given load:"))
z= int(input("Enter the distance of vertical stress:"))
r= int(input("Enter the distance ofhorizntal stress:"))
stress = ((3*Q*(1/(1+(r/z)**2))**2.5))/(2*3.14*(z**2))
print("The value of stress is", stress)

"""ASSIGNMENT NO 7 - APPLICATION OF PYTHON IN THE FIELD OF FOUNDATION ENGINEERING

Q-1
"""

#To Determine the bearing capacity of soil with water table
BulkDensity =float(input("Enter the value of Bulk Density of soil:"))
SatDensity = float(input("Enter the value of Saturated Density of soil:"))
WaterDensity = float(input("Enter the unit Weight of Water:"))
Df= float(input("Enter the value of depth of footing:"))
Dw = float(input("Enter the value of water table above footing level:"))
Dw1= float(input("Enter the value of Water table below the level of footing:"))
B= float(input("Enter the value of width of footing:"))
Nq= float(input("Enter the vaiue of Nq:"))
N= float(input("Enter the value of N ganna (N):"))
SubDensity=float(input())
print("Submerged Weight of soil is:", SubDensity)
#The bearing capacity of soil when water table is at ground print("CASE A")
qu=(SubDensity*Df*Nq)+(0.5*0.8*B*SubDensity*N)
print("The value of ultimate bearing capacity of soil is:", qu)
#Approximate calculation of Bearing capacity of soil is.
Rw= 0.5+0.5*(Dw/B)
print("The value of Rw is:", Rw)
Rw1=0.5+0.5*(Dw1/8)
print("The value of Rw1 is:", Rw1)
qu=(BulkDensity*Df*Nq*Rw) + (0.5*0.8*8*BulkDensity*N*Rw1)
print("The value ultimate bearing capacity of soil is:", qu)
# Case B
print("CASE B")
qu=(BulkDensity*Df*Nq)+(0.5*0.8*8*SubDensity)
print("The value of ultimate bearing capacity is:", qu)
Dw = float(input("Enter the value of water table above footing level:"))
Dw1 = float(input("Enter the value of Water table below the level of footing:"))
print("The approximate value of ultimate bearing capacity is: ")
Rw=0.5+0.5*(Dw/B)
print("The value of Rw is:", Rw)
Rw1= 0.5 + 0.5* (Dw1/8)
print("The value of Rw1 is:", Rw1)
qu=(BulkDensity*Df*Nq*Rw)+(0.5*0.8*8*BulkDensity*Rw1)
print("The approximate value of ultimate hearing capacity is: ", qu)
# Case C
print("CASE C")
x = float(input("Enter the value of depth of water below footing:"))
qu=(BulkDensity*Df*Nq)+(0.5*0.8*((BulkDensity*x)+(SubDensity*(B-x)))*N)
print("The value of ultimate bearing capacity is:", qu)
Dw = float(input("Enter the value of water table above footing level:"))
Dw1= float(input("Enter the value of Water table below the level of footing:"))
print("The approximate value of ultimate bearing capacity is:")
Rw= 8.5+ 8.5*(Dw/B)
print("The value of Rw is:", Rw)
Rw1 = 0.5 + 0.5*(Dw1/8)
print("The value of Rwl is: ", Rw1)
qu= (BulkDensity*Df*Nq*Rw)+(0.5*0.8*8*BulkDensity*N*Rw1)
print("the value of ultimate bearing capaciy is:", qu)

"""Q-2"""

#To find the ultimate load carring capacity of pile
UCS = float(input("Enter the value of UCS of soil:"))
Cu = UCS/2
B = float(input("Enter the value of dimension of pile:"))
a=float(input("Enter the length of pile:"))
Alpha =float(input("Enter the value of adhesion factor:"))
Nc=float(input("The value of Nc: "))
Ab=B*B
print("the Base area of footing is:", Ab)
As=4*B*a
print("The value of chohesion of soil is:", Cu)
Qpu=Cu*Nc*Ab
print("'Qpu:", Qpu)
Qf=Alpha*Cu*As
print("Qf:", Qf)
Qu=Qpu+Qf
print("the value of load carring capacity of pile is (Qu):", Qu)

"""Q-3"""

# To Determine the bearing capacity of soil with water table
BulkDensity = float(input("Enter the value of Bulk Density of soil:"))
SatDensity = float(input("Enter the value of Saturated Density of soil:"))
WaterDensity = float(input("Enter the unit Weight of Water:"))
Df = float(input("Enter the value of depth of footing:"))
B = float (input ("Enter the value of width of footing:"))
Nq = float(input("Enter the value of Ng:"))
N_Gamma = float (input ("Enter the value of N gamma (N):"))
SubDensity = SatDensity - WaterDensity
print ("Submerged Weight of soil is:", SubDensity)
M = int (input("Number of data values of Water table above footing level: "))
N = int (input("Number of data values of Water table below footing level: "))
Dw = []
Dw1 = []
for i in range (1, M+1) :
  print ("Enter the value of water table above footing level measured w.r.t. ground (Dw) :")
  Depth_Dw = float(input())
  Dw.append(Depth_Dw)
  Rw =0.5+0.5*(Depth_Dw/B)
  print("The value of Rw is:", Rw)
for j in range (1, N+1):
  print("Enter the value of water table above footing level measured w.r.t. ground (Dw1): ")
  Depth_Dw1 = float(input())
  Dw.append(Depth_Dw1)
  Rw1 =0.5+0.5*(Depth_Dw1/B)
  print("The value of Rw1 is:", Rw1)
  qu=(BulkDensity*Df*Nq*Rw)+(0.5*0.8*B*BulkDensity*N_Gamma*Rw1)

"""ASSIGNMENT NO 8 - APPLICATION OF PYTHON IN THE FIELD OF WATER SUPPLY ENGINEERING

Q-1
"""

#To determine alkalinity of given sample
H2SO4_req = float(input("Enter the volume ofH2SO4 required in ml:"))
Sample = float(input("Enter the value of sample inlitres:"))
Alkalinity_Removed=H2SO4_req
print("Alkalinity_Removed:", Alkalinity_Removed,"mg")
Alk_mg_per_lit = Alkalinity_Removed/ Sample
print("Total Alkalinity:",Alk_mg_per_lit,"mg/lit")
OH= float (input("Enter the value of OH-Alkalinity present : "))
#Alkalinity removed till pH of 8.3
H2SO4_req = float (input("Enter the volume ofH2S04 required in ml :"))
Alkalinity_Removed = H2SO4_req
print("Alkalinity_Removed: ",Alkalinity_Removed, "mg")
CO3_Combined = Alkalinity_Removed/Sample
print ("Carbonate Alkalinity upto pH8.3:",CO3_Combined, "mgperlit" )
CO3=CO3_Combined-OH
print("Carbonate Alkalinity:", CO3,"'mg/lit")
HCO3 =Alk_mg_per_lit - 2*CO3-OH
print("Bicarbonate Alkalinity:", HCO3, "mg/it")

"""ASSIGNMENT NO 9 -APPLICATION OF PYTHON IN THE FIELD OF WASTE WATER ENGINEERING

Q-1
"""

#To find BOD at 7th day 25C
#To find Decay Coefficient at 25C
K1=float(input("Decay Coefficient:"))
T= int(input("Temperature of 3rd day BOD:"))
T1=int(input("Temperature of 7th day BOD:"))
K2 = (K1*(1.047)**(T1-T))
print("The value ofK2 is:", K2)
#To find Ultimate BOD
e=float("2.718")
print("The value ofe is:", e)
B1=float(input("BOD at 3rd day 20c:"))
t=float(input("time in days for finding B1:"))
E=(1-e**(-0.23*t))
print("The value ofE is:", E)
l0=(B1/E)
print("The value of 10 is:", l0)
#To find BOD at 7th day 25C
#B2 = float(input("BoD at 7rd day 25c:"))
t1 =float(input("time in days for findinfB2:"))
E1 =(1-e**(-0.289*t1))
print("The value ofEl is:", E1)
B2 = (l0*E1)
print("The value of B2 is:", B2)

"""Q-2"""

#Determination if density of sludge removed from aeration tank
M= float(input("Enter the value of initial mass :"))
S=float(input("Enter the value ofsolid containing sludge inpercentage:"))
Gs= float(input("Enterthe value of Specific gravity ofsludge solid:"))
Rho_W= float(input("Enter the value of density of water:"))
Ws = ((S/M)*100)
m =M- Ws
print("the value ofmass of water", m)
print("The value of Solid Content in sludge", Ws)
Vw =m/Rho_W
print("The Value of Volume", Vw)
Rho_S =Gs*Rho_W
print("The value ofDensity of solid content in sludge", Rho_S)
Vs=(Ws/(Gs*Rho_S))
print("The value of volume of solid content in sludge", Vs)
Vt=Vw+Vs
print("The value of total volume of solid content in sludge", Vt)
Rho_SL= M/Vt
print("The value of Density of sludge removed from aeration", Rho_SL)

"""ASSIGNMENT NO 10 - APPLICATION OF PYTHON IN THE FIELD OF DESIGN OF STEEL STRUCTURE

Q-1
"""

# Design of tension member
Tu=float(input("Enter the value of ultimate tensile strength:"))
fy=float(input("Enter the value of yield strength of steel:"))
fu= float(input("Enter the value of ultimate strength of steel:"))
fub=float(input("Enter the value of ultimate strength of bolt:"))
Gamma_mo= float(input("Enter the value of partial factor of safety Garmma mo:"))
Gamma_m1= float(input("Enter the value of partial factor of safety Garmma_m1:"))
Gamma_mb= float(input("Enter the value of partial factor of safety Gamma_mb:"))
print("Gross Area Required")
Agreq=1.1*Tu*1000/fy
print("The value of gross area required is:", 1.2*Agreq)
#Selection of section
#Selecting ISA 100x65x8
Ag= float(input("Enter the value of gross area of steel is:"))
Lcl= float(input("Enter the length of connected leg:"))
Lol= float(input("Enter the length of outstand leg:"))
t= float(input("Entert the value of least thickness: "))
Ag= 1257
#Design of connections
d= float(input("Enter the value of diameter of bolt:"))
do=d+2
print("The diameter of bolt hole is:", do)
# As per IS code minimum pitch distance is
pmin =2.5*d
print("The minimum pitch is:", pmin)
#Edge distance as per IS 800 is
e=1.5*do
print("Enter the value of edge distance:", e)
nn=float(input("Number of shear planes with threaded intercepting the shear plane:"))
ns= float(input("Number of shear plane without threads:"))
Anb=0.78*0.7854*d*d
print("threaded area of bolt is:", Anb)
Asb=0.7854*d*d
print("plane shank area of bolt is:", Asb)
Vdsb=(fub/(1.732*Gamma_mb)*(nn*Anb+ns*Asb)*10**-3)
print("The value of Vdsb:", Vdsb)
kb1=e/(3*do)
print("Kb1:", kb1)
kb2=(pmin/(3*do))-0.25
print("Kb2:", kb2)
kb3=fub/fu
print("Kb3:", kb3)
kb4 = 1
print("Kb4:", kb4)
kb= min(kb1,kb2,kb3,kb4)
print("Kb:", kb)
Vdpb=(2.5*kb*d*t*fu*10**-3)/Gamma_mb
print("Vdpb:", Vdpb)
Vd = min(Vdsb ,Vdpb)
print("Vd:", Vd)
N=Tu/Vd
print("Number of bolts requird:", N)
N= float(input("Enter the value of number of bolts:"))
# Check for strength
# Criteria 1 Yeilding of Gross Section
Tdg=(Ag*fy*10-3)/Gamma_mo
print("The value of tensile strength due to yielding of gross section is:", Tdg)
# Criteria 2 Rupture
Anc = (Lcl-(t/2)-do)*t
print("Net Area of Connecting leg is: (Anc):", Anc)
Ago=(Lol-(t/2))*t
print("Gross Area of outstand leg is: (Anc):", Ago)
Lc=(N-1)*pmin
print("Le:", Lc)
bs=(0.6*Lcl)+(Lol*t)
print("bs:", bs)
Beta1=((fu/Gamma_m1)*(fy/Gamma_mo))
print("Beta:1", Beta1)
Beta2=(1.4-(0.076*(fy/fu)*(bs/Lc)*(Lol/t)))
print("Beta:2", Beta2)
Beta=min(Beta1,Beta2)
print("Beta:",Beta)
print("Check 1")
if Beta>1.4:
  print("Not Safe")
else:
  print("Safe")
  print("Check 2")
if Beta<0.7:
  print("Not Safe")
else:
  print("Safe")
Tdn=((0.9*fu*Anc)/Gamma_m1) + (Beta*Ago*fy/Gamma_mo)
print("'Tdn:", Tdn)
# Criteria 3 Block Shear
Avg=(pmin*(N-1)+e)*t
print("Avg:", Avg)
Avn=((pmin*(N-1) +e)-(N-1)*do+(8.5* do))*t
print("Avn:", Avn)
Atg=0.6*Lcl*t
print("Atg:", Atg)
Atn= Atg*(0.5*do)
print("Atn:", Atn)
Tb1 =((Avg*fy)/(1.732 *Gamma_mo))+((0.9* fu*Atn)/(Gamma_m1))*10**-3
print("Tb1:", Tb1)
Tb2 =((0.9*Avn*fu)/(1.732* Gamma_m1))+((Atg*fy)/(Gamma_mo))*10**-3
print("Tb2:", Tb2)
Tb = min(Tb1, Tb2)
print("Tb", Tb)
Td = min(Tdg,Tb)
print("Td", Td)
if Td>Tu:
  print("SAFE")
else:
  print("Revise the Section")